### ISSUE TITLE
GitHub Action with deployment URL not working from forks

### ISSUE THREAD

**Issue by met** [cesko-digital/movapp#21]
Zjistil jsem, že ta vychytávka, cos přidával https://github.com/cesko-digital/movapp/pull/19 , aby komentovala URL každého pull requestu nefunguje, když ten PR provedu z github forku.

Udělá to [tuhle chybu](https://github.com/cesko-digital/movapp/actions/runs/2003620761):

**[Add deployment URL](https://github.com/cesko-digital/movapp/runs/5599066392?check_suite_focus=true)
Resource not accessible by integration**

Zrovna jsem chtěl vyškolit Terezu, která s Gitem neumí, jak by mohla upravovat věci na webu githubu a přišlo mi, že je bezpečnější, aby to dělala ve svém github forku a z něj nám posílala PR (protože jinak bude muset řešit větve a to je složité), tak jsem na to narazil.

Má to snadné řešení?
Jinak je matoucí, že se podmínky PR ukážou, že selhali, když neproběhl tenhle krok.

**Comment by zoul** [comment]
Nedošlo mně, že ty Actions běží i ve forcích. Jedna možnost je zakázat na záložce [Settings → Actions](https://github.com/cesko-digital/movapp/settings/actions) v tom forku provádění Actions. Ale lepší řešení by bylo zkontrolovat u téhle konkrétní, že běžíme v tom našem repu – pošlu k tomu PR. A souhlas, je to milá drobnost, kterou ale nemá smysl udržovat při životě, pokud bude dělat problémy.

**Comment by zoul** [comment]
Zajímavý je, že GitHub standardně Actions ve forcích vypíná:

<img width="909" alt="forks" src="https://user-images.githubusercontent.com/95329/159130523-49d5c35a-b35e-431c-9950-a4e64b76c257.png">

Vy jste je v tom forku ručně zapnuli? Kvůli testům, nebo kvůli čemu?

**Comment by zoul** [comment]
Zkusil jsem teď udělat nový fork a v něm [nový PR](https://github.com/zoul/movapp/pull/2) a funguje to správně, akce neproběhne, respektive [přeskočí se](https://github.com/zoul/movapp/runs/5612461653?check_suite_focus=true). V čem tedy může být rozdíl u toho jejího forku?

**Comment by met** [comment]
@zoul Dívám se na to, Tereza si udělala fork taky až dneska.

Ale vidím jeden rozdíl. Neučil jsem Terezu dělat větve. Bylo to její první setkání s Gitem a Githubem, šli jsme pomalu, takže si udělala změny ve forku main a z těch PR. Bude problém v tomhle?

👉 merged 1 commit into cesko-digital:main **from javoreza:main**
👉 merge 1 commit into main **from zoul-patch-2**

Pokud by vadilo tohle, tak Terezu později doučím dělat větve a zatím to dočasně přežijeme.

**Comment by zoul** [comment]
Hm, konečně jsem myslím našel hlavní příčinu, [dokumentace tady](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token). Problém není ve spouštění Actions ve forku, jak jsem si prve blbě myslel, problém jsou PRs z forků, kde GitHub standardně vynucuje token pouze pro čtení. To by mělo jít dořešit, měli bysme být schopni přeskočit workflow, pokud nemáme právo zápisu. Vrátím se k tomu.

**Comment by zoul** [comment]
Smazal jsem :)
