### ISSUE TITLE
Přidat baruska do týmu

### ISSUE THREAD

**Issue by met** [cesko-digital/movapp#30]
Prosím o přidání https://github.com/baryska do týmu movapp.

Dal jsem jí práva přímo do movapp repozitáře, ale stále ji nemůžu přidat do členů movapp týmu (mám aktivní tlačítko na přidání členů, ale napíše mi to, že není členem Č.D a tak ji přidat nemůžu).

**Comment by zoul** [comment]
Hotovo.
