### ISSUE TITLE
Alias privyt pro email

### ISSUE THREAD

**Issue by met** [cesko-digital/movapp#52]
Prosím, přidej k emailům co máme i alias privyt@movapp.cz (je tam prohozene tvrde a mekke o oproti ofocialnimi pryvit@ )

Koukám, že [jsme to už jednou spletli](https://twitter.com/pionl/status/1508507144387284999?s=21&t=MOj2NeQt5azi63iaSEgn9g) a nejspíš se to může plést i do budoucna.

**Comment by zoul** [comment]
Hotovo!
