### ISSUE TITLE
Parts of the website still refer to Czechia regardless of language mutation

### ISSUE THREAD

**Issue by dynga** [cesko-digital/movapp#97]
1. The links in the footer still point to Czech websites, which aren't going to be of much use to anybody in Poland. For the Polish language mutation I suggest switching them out for, in order from the left:
    - Pomahej Ukrajině for https://www.gov.pl/ua (Ukrainian version of Poland's e-government website, also contains useful government-related info in Ukrainian)
        - Title (both languages): "gov.pl/ua"
        - Descriptions (pl/ua): "Wersja portalu gov.pl dla obywateli Ukrainy" / "Сайт Республіки Польща для громадян України"
    - Stojíme za Ukrajinou for https://pomagamukrainie.gov.pl (Polish counterpart of both Pomahej Ukrajině and Stojíme za Ukrajinou)
        - Title (both languages) : "#PomagamUkrainie"
        - Descriptions (pl/ua): "Portal pośredniczący ofertom pomocy" / "Майданчик з пропозиціями допомоги"
    - Czech version of Česko.Digital's website for the English version. Czech is really similar to Polish, but its different writing system makes it pretty hard to read for Poles so I think English will be the "lesser of two evils". The translation already mentions the link being in English (the part in parentheses), I just didn't consider while initially translating that the link itself is elsewhere and is not going to carry over while merging my translation.

    This *might*, but doesn't neccesarily *have to* also apply to Slovakia. I've no idea, a Slovak person needs to be consulted on this I think.

2.  /public/locales/uk/common.json contains only SEO mentioning Czechs. Not critical, but it's gonna be a bit weird when an Ukrainian in Poland sees "Movapp.eu - so Czechs and Ukrainians can undestand each other better" in the main page's title. We'd either have to come up with something nationality-neutral, or make it switch like other parts of the Ukrainian locale.
Same issue applies to the About page - it mentions Movapp being a Czech-Ukrainian dictionary regardless of what language mutation the user is using.

3. A *very* minor thing, but on mouse hover over the licence name in the footer, a pop-up is displayed explaining what the licence stands for. This is also always in Czech regardless of the language one is browsing the website in.

4. EDIT: After posting this I also noticed that the Ukrainian alphabet page seems to always show Czech transcriptions instead of the ones relevant to the language mutation. No matter what I put in /data/alphabets/pl/ua_alphabet.ts, the page still displays Czech content. Sadly, I don't know TypeScript well enought to debug it so I'm unable to completely rule out that this isn't something on my end, but I'm *mostly* sure.
This probably isn't a problem for Slovak since I guess the transcriptions are the same, but for Polish it is since people will just read "š" as "s" and so on.

**Comment by met** [comment]
@dynga Is there anything more that needs to be done. Or can we close it?
